version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: ./app/Dockerfile
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app:/app
        ports:
            - 8000:8000
        depends_on:
            - db
            - redis
        environment:
           DATABASE_URL: 'postgres://postgres:@db:5432/postgres'

    db:
        image: postgres:11.2
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
    redis:
      container_name: redis
      image: redis:5.0.3
